// This file was generated by liblab | https://liblab.com/

namespace NhlStats.Http.Serialization;

public enum QuerySerializationStyle
{
    Form = SerializationStyle.Form,
    SpaceDelimited = SerializationStyle.SpaceDelimited,
    PipeDelimited = SerializationStyle.PipeDelimited,
    DeepObject = SerializationStyle.DeepObject
}
