// This file was generated by liblab | https://liblab.com/

using NhlStatsClient;
using NhlStatsClient.Config;
using Environment = NhlStatsClient.Http.Environment;

var config = new NhlStatsClientConfig { Environment = Environment.Default };

var client = new NhlStatsClientClient(config);

var response = await client.Miscellaneous.PingServerAsync();

Console.WriteLine(response);
