// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using NhlStats.Http;
using NhlStats.Http.Exceptions;
using NhlStats.Http.Extensions;
using NhlStats.Http.Serialization;

namespace NhlStats.Services;

public class GoaliesService : BaseService
{
    internal GoaliesService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>Retrieve goalie leaders for a specific attribute.</summary>
    /// <param name="attribute">Goalie attribute</param>
    /// <param name="lang">Language code</param>
    public async Task<object> GetGoalieLeadersAsync(
        string attribute,
        string lang,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(attribute, nameof(attribute));
        ArgumentNullException.ThrowIfNull(lang, nameof(lang));

        var request = new RequestBuilder(HttpMethod.Get, "{lang}/leaders/goalies/{attribute}")
            .SetPathParameter("attribute", attribute)
            .SetPathParameter("lang", lang)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Retrieve goalie stats for a specific report.</summary>
    /// <param name="report">Goalie report</param>
    /// <param name="lang">Language code</param>
    /// <param name="cayenneExp">Required</param>
    /// <param name="isAggregate">Optional</param>
    /// <param name="isGame">Optional</param>
    /// <param name="factCayenneExp">Optional</param>
    /// <param name="include">Optional</param>
    /// <param name="exclude">Optional</param>
    /// <param name="sort">Optional</param>
    /// <param name="dir">Optional</param>
    /// <param name="start">Optional</param>
    /// <param name="limit">Optional (Note: a limit of -1 will return all results)</param>
    public async Task<object> GetGoalieStatsAsync(
        string report,
        string lang,
        string cayenneExp,
        bool? isAggregate = null,
        bool? isGame = null,
        string? factCayenneExp = null,
        string? include = null,
        string? exclude = null,
        string? sort = null,
        string? dir = null,
        long? start = null,
        long? limit = null,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(report, nameof(report));
        ArgumentNullException.ThrowIfNull(lang, nameof(lang));
        ArgumentNullException.ThrowIfNull(cayenneExp, nameof(cayenneExp));

        var request = new RequestBuilder(HttpMethod.Get, "{lang}/goalie/{report}")
            .SetPathParameter("report", report)
            .SetPathParameter("lang", lang)
            .SetQueryParameter("cayenneExp", cayenneExp)
            .SetOptionalQueryParameter("isAggregate", isAggregate)
            .SetOptionalQueryParameter("isGame", isGame)
            .SetOptionalQueryParameter("factCayenneExp", factCayenneExp)
            .SetOptionalQueryParameter("include", include)
            .SetOptionalQueryParameter("exclude", exclude)
            .SetOptionalQueryParameter("sort", sort)
            .SetOptionalQueryParameter("dir", dir)
            .SetOptionalQueryParameter("start", start)
            .SetOptionalQueryParameter("limit", limit)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Retrieve goalie milestones.</summary>
    /// <param name="lang">Language code</param>
    public async Task<object> GetGoalieMilestonesAsync(
        string lang,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(lang, nameof(lang));

        var request = new RequestBuilder(HttpMethod.Get, "{lang}/milestones/goalies")
            .SetPathParameter("lang", lang)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
