// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using NhlStatsClient.Http;
using NhlStatsClient.Http.Exceptions;
using NhlStatsClient.Http.Extensions;
using NhlStatsClient.Http.Serialization;

namespace NhlStatsClient.Services;

public class PlayersService : BaseService
{
    internal PlayersService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>Retrieve player information. Currently seems to return a truncated list with a total.</summary>
    /// <param name="lang">Language code</param>
    public async Task<object> GetPlayerInformationAsync(
        string lang,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(lang, nameof(lang));

        var request = new RequestBuilder(HttpMethod.Get, "{lang}/players")
            .SetPathParameter("lang", lang)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
