// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using NhlStatsClient.Http;
using NhlStatsClient.Http.Exceptions;
using NhlStatsClient.Http.Extensions;
using NhlStatsClient.Http.Serialization;

namespace NhlStatsClient.Services;

public class TeamsService : BaseService
{
    internal TeamsService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>Retrieve list of all teams.</summary>
    /// <param name="lang">Language code</param>
    public async Task<object> GetTeamInformationAsync(
        string lang,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(lang, nameof(lang));

        var request = new RequestBuilder(HttpMethod.Get, "{lang}/team")
            .SetPathParameter("lang", lang)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Retrieve team stats for a specific report.</summary>
    /// <param name="report">Team report</param>
    /// <param name="lang">Language code</param>
    /// <param name="isAggregate">Optional</param>
    /// <param name="isGame">Optional</param>
    /// <param name="factCayenneExp">Optional</param>
    /// <param name="include">Optional</param>
    /// <param name="exclude">Optional</param>
    /// <param name="cayenneExp">Optional</param>
    /// <param name="sort">Optional</param>
    /// <param name="dir">Optional</param>
    /// <param name="start">Optional</param>
    /// <param name="limit">Optional (Note: a limit of -1 will return all results)</param>
    public async Task<object> GetTeamStatsAsync(
        string report,
        string lang,
        bool? isAggregate = null,
        bool? isGame = null,
        string? factCayenneExp = null,
        string? include = null,
        string? exclude = null,
        string? cayenneExp = null,
        string? sort = null,
        string? dir = null,
        long? start = null,
        long? limit = null,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(report, nameof(report));
        ArgumentNullException.ThrowIfNull(lang, nameof(lang));

        var request = new RequestBuilder(HttpMethod.Get, "{lang}/team/{report}")
            .SetPathParameter("report", report)
            .SetPathParameter("lang", lang)
            .SetOptionalQueryParameter("isAggregate", isAggregate)
            .SetOptionalQueryParameter("isGame", isGame)
            .SetOptionalQueryParameter("factCayenneExp", factCayenneExp)
            .SetOptionalQueryParameter("include", include)
            .SetOptionalQueryParameter("exclude", exclude)
            .SetOptionalQueryParameter("cayenneExp", cayenneExp)
            .SetOptionalQueryParameter("sort", sort)
            .SetOptionalQueryParameter("dir", dir)
            .SetOptionalQueryParameter("start", start)
            .SetOptionalQueryParameter("limit", limit)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Retrieve list of all franchises.</summary>
    /// <param name="lang">Language code</param>
    public async Task<object> GetFranchiseInformationAsync(
        string lang,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(lang, nameof(lang));

        var request = new RequestBuilder(HttpMethod.Get, "{lang}/franchise")
            .SetPathParameter("lang", lang)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
